name: Generate css vars from tokens and copy
on: [push]

jobs:
  build_tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npx token-transformer input/design-tokens.json input/base.json base
      - run:
          npx token-transformer input/design-tokens.json input/brand-a.json
          base,brand-a base --expandTypography=true
      - run:
          npx token-transformer input/design-tokens.json input/brand-b.json
          base,brand-b base --expandTypography=true
      - run: node build.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build tokens
  copy_tokens:
    runs-on: ubuntu-latest
    needs: [build_tokens]
    steps:
      - uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          src_branch: feature
          src_path: output/.
          dst_owner: Tangcuyu
          dst_repo_name: stencil-storybook-token-demo
          dst_branch: main
          dst_path: src/css/.
          username: tangcuyu
          email: joysmshr@126.com
          commit_message: copy css tokens
  copy_tokens_tographclient:
    runs-on: ubuntu-latest
    needs: [build_tokens]
    steps:
      - uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          src_branch: feature
          src_path: output/.
          dst_owner: Tangcuyu
          dst_repo_name: graphClient
          dst_branch: mainfeature-designtokens
          dst_path: src/styles/css/.
          username: tangcuyu
          email: joysmshr@126.com
          commit_message: copy base css tokens from token-demo-src repo
